// Generated by CoffeeScript 1.3.1
var RYB, display, generate, numberColors,
  __slice = [].slice;

RYB = {
  white: [1, 1, 1],
  red: [1, 0, 0],
  yellow: [1, 1, 0],
  blue: [0.163, 0.373, 0.6],
  violet: [0.5, 0, 0.5],
  green: [0, 0.66, 0.2],
  orange: [1, 0.5, 0],
  black: [0.2, 0.094, 0.0],
  rgb: function() {
    var b, i, r, ryb, y, _i, _ref, _results;
    ryb = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    _ref = ryb.map(function(t) {
      return t * t * (3 - 2 * t);
    }), r = _ref[0], y = _ref[1], b = _ref[2];
    _results = [];
    for (i = _i = 0; _i <= 2; i = ++_i) {
      _results.push(RYB.white[i] * (1 - r) * (1 - b) * (1 - y) + RYB.red[i] * r * (1 - b) * (1 - y) + RYB.blue[i] * (1 - r) * b * (1 - y) + RYB.violet[i] * r * b * (1 - y) + RYB.yellow[i] * (1 - r) * (1 - b) * y + RYB.orange[i] * r * (1 - b) * y + RYB.green[i] * (1 - r) * b * y + RYB.black[i] * r * b * y);
    }
    return _results;
  }
};

generate = document.getElementById('generate');

numberColors = document.getElementById('number-colors');

display = document.getElementById('colors');

generate.addEventListener('click', function(event) {
  var b, base, el, g, n, number, r, _i, _ref, _results;
  event.preventDefault();
  while (display.firstChild) {
    display.removeChild(display.firstChild);
  }
  number = parseInt(numberColors.value, 10);
  base = Math.ceil(Math.pow(number, 1 / 3));
  _results = [];
  for (n = _i = 0; 0 <= number ? _i < number : _i > number; n = 0 <= number ? ++_i : --_i) {
    _ref = RYB.rgb(Math.floor(n / (base * base)) / (base - 1), Math.floor(n / base % base) / (base - 1), Math.floor(n % base) / (base - 1)).map(function(x) {
      return Math.floor(255 * x);
    }), r = _ref[0], g = _ref[1], b = _ref[2];
    el = document.createElement("div");
    el.setAttribute("class", "color");
    el.style.backgroundColor = "rgb(" + r + ", " + g + ", " + b + ")";
    _results.push(display.appendChild(el));
  }
  return _results;
});
